"""Generate IDE-specific MCP configs and agent integrations."""

from __future__ import annotations

import json
from pathlib import Path


def detect_ides(project_root: Path) -> list[str]:
    """Detect which IDEs are in use based on directory markers."""
    detected = []
    if (project_root / ".vscode").exists():
        detected.append("vscode")
    if (project_root / ".cursor").exists():
        detected.append("cursor")
    if (project_root / ".idea").exists():
        detected.append("jetbrains")
    if (project_root / ".github").exists():
        detected.append("copilot_cli")
    if (project_root / ".windsurf").exists():
        detected.append("windsurf")
    return detected


def generate_vscode_mcp(project_root: Path, wiki_subdir: str = ".llmwiki") -> Path:
    """Generate .vscode/mcp.json for VS Code Copilot."""
    vscode_dir = project_root / ".vscode"
    vscode_dir.mkdir(exist_ok=True)
    config = {
        "servers": {
            "llmwiki": {
                "type": "stdio",
                "command": "llmwiki",
                "args": ["mcp"],
                "cwd": "${workspaceFolder}/" + wiki_subdir,
            }
        }
    }
    out = vscode_dir / "mcp.json"
    out.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return out


def generate_cursor_mcp(project_root: Path, wiki_subdir: str = ".llmwiki") -> Path:
    """Generate .cursor/mcp.json for Cursor."""
    cursor_dir = project_root / ".cursor"
    cursor_dir.mkdir(exist_ok=True)
    config = {
        "mcpServers": {
            "llmwiki": {
                "command": "llmwiki",
                "args": ["mcp"],
                "cwd": wiki_subdir,
            }
        }
    }
    out = cursor_dir / "mcp.json"
    out.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return out


def generate_jetbrains_mcp(project_root: Path, wiki_subdir: str = ".llmwiki") -> Path:
    """Generate .idea/ai-mcp.json for JetBrains AI."""
    idea_dir = project_root / ".idea"
    idea_dir.mkdir(exist_ok=True)
    config = {
        "mcpServers": {
            "llmwiki": {
                "command": "llmwiki",
                "args": ["mcp"],
                "cwd": wiki_subdir,
            }
        }
    }
    out = idea_dir / "ai-mcp.json"
    out.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return out


def generate_windsurf_mcp(project_root: Path, wiki_subdir: str = ".llmwiki") -> Path:
    """Generate .windsurf/mcp.json for Windsurf."""
    ws_dir = project_root / ".windsurf"
    ws_dir.mkdir(exist_ok=True)
    config = {
        "mcpServers": {
            "llmwiki": {
                "command": "llmwiki",
                "args": ["mcp"],
                "cwd": wiki_subdir,
            }
        }
    }
    out = ws_dir / "mcp.json"
    out.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return out


def generate_copilot_extension(project_root: Path, wiki_subdir: str = ".llmwiki") -> Path:
    """Generate .github/extensions/llmwiki-search/extension.mjs for Copilot CLI.

    Uses the Copilot SDK bundled with the CLI (``@github/copilot-sdk/extension``)
    to register a ``llmwiki_search`` tool and a ``/wikisearch`` slash command
    via ``joinSession()``.
    """
    ext_dir = project_root / ".github" / "extensions" / "llmwiki-search"
    ext_dir.mkdir(parents=True, exist_ok=True)
    js = '''// LLMWiki Search Extension for Copilot CLI
// Auto-generated by `llmwiki setup-agent`

import { joinSession } from "@github/copilot-sdk/extension";
import { execSync } from "child_process";
import { join } from "path";

function runSearch(query, wikiDir, flags = "--agent") {
  try {
    return execSync(
      `llmwiki search "${query}" ${flags} --config ${wikiDir}/llmwiki.json`,
      { encoding: "utf-8", timeout: 10000, cwd: wikiDir },
    );
  } catch (e) {
    return JSON.stringify({ error: e.message });
  }
}

function runGet(pageId, wikiDir) {
  try {
    return execSync(
      `llmwiki get "${pageId}" --config ${wikiDir}/llmwiki.json`,
      { encoding: "utf-8", timeout: 10000, cwd: wikiDir },
    );
  } catch (e) {
    return JSON.stringify({ error: e.message });
  }
}

function runQuery(sql, wikiDir) {
  try {
    return execSync(
      `llmwiki query "${sql.replace(/"/g, '\\\\"')}" --json --config ${wikiDir}/llmwiki.json`,
      { encoding: "utf-8", timeout: 10000, cwd: wikiDir },
    );
  } catch (e) {
    return JSON.stringify({ error: e.message });
  }
}

const session = await joinSession({
  tools: [
    {
      name: "llmwiki_search",
      description:
        "Search the LLMWiki knowledge base for this project. Returns " +
        "page IDs, titles, categories, and method signatures. Use --method " +
        "flag to search for a specific method/function by name. Call this " +
        "tool BEFORE reading raw source files to save tokens.",
      parameters: {
        type: "object",
        properties: {
          query: {
            type: "string",
            description: "Search query (keywords, method names, or concepts)",
          },
          method: {
            type: "boolean",
            description: "If true, search specifically for a method/function declaration by name",
          },
        },
        required: ["query"],
      },
      handler: async ({ query, method }) => {
        const wikiDir = join(process.cwd(), "''' + wiki_subdir + '''");
        const flags = method ? "--method --agent" : "--agent";
        return runSearch(query, wikiDir, flags);
      },
    },
    {
      name: "llmwiki_get",
      description:
        "Get full wiki page content by page ID. Returns structured " +
        "content with method signatures, imports, and documentation. " +
        "Use after llmwiki_search to get details for a specific page.",
      parameters: {
        type: "object",
        properties: {
          page_id: {
            type: "string",
            description: "Page ID from search results (e.g. com-vf-core-utility/auditutil)",
          },
        },
        required: ["page_id"],
      },
      handler: async ({ page_id }) => {
        const wikiDir = join(process.cwd(), "''' + wiki_subdir + '''");
        return runGet(page_id, wikiDir);
      },
    },
    {
      name: "llmwiki_query",
      description:
        "Run a read-only SQL query against the wiki database. " +
        "Use for advanced lookups: FTS5 search, aggregations, joins. " +
        "Tables: pages (id, title, category, importance_score, language), " +
        "pages_fts (title, body_plain, tags, category — use MATCH).",
      parameters: {
        type: "object",
        properties: {
          sql: {
            type: "string",
            description: "SQL SELECT query to execute",
          },
        },
        required: ["sql"],
      },
      handler: async ({ sql }) => {
        const wikiDir = join(process.cwd(), "''' + wiki_subdir + '''");
        return runQuery(sql, wikiDir);
      },
    },
  ],
  commands: [
    {
      name: "wikisearch",
      description: "Search the LLMWiki knowledge base (usage: /wikisearch <query>)",
      handler: async (ctx) => {
        const query = (ctx.args ?? "").trim();
        if (!query) {
          await session.log(
            "Usage: /wikisearch <query>\\n" +
            "Example: /wikisearch authentication flow",
            { level: "info" },
          );
          return;
        }
        const wikiDir = join(process.cwd(), "''' + wiki_subdir + '''");
        const result = runSearch(query, wikiDir);
        await session.log(result, { level: "info" });
      },
    },
  ],
});
'''
    out = ext_dir / "extension.mjs"
    out.write_text(js, encoding="utf-8")
    return out


def setup_all(project_root: Path, wiki_subdir: str = ".llmwiki",
              targets: list[str] | None = None) -> list[str]:
    """Generate configs for requested targets. Returns list of created file paths."""
    generators = {
        "vscode": generate_vscode_mcp,
        "cursor": generate_cursor_mcp,
        "jetbrains": generate_jetbrains_mcp,
        "windsurf": generate_windsurf_mcp,
        "copilot_cli": generate_copilot_extension,
    }
    if targets is None:
        targets = list(generators.keys())
    created = []
    for target in targets:
        gen = generators.get(target)
        if gen:
            path = gen(project_root, wiki_subdir)
            created.append(str(path))
    return created
