"""Generate IDE-specific MCP configs and agent integrations."""

from __future__ import annotations

import json
from pathlib import Path


def detect_ides(project_root: Path) -> list[str]:
    """Detect which IDEs are in use based on directory markers."""
    detected = []
    if (project_root / ".vscode").exists():
        detected.append("vscode")
    if (project_root / ".cursor").exists():
        detected.append("cursor")
    if (project_root / ".idea").exists():
        detected.append("jetbrains")
    if (project_root / ".github").exists():
        detected.append("copilot_cli")
    if (project_root / ".windsurf").exists():
        detected.append("windsurf")
    return detected


def generate_vscode_mcp(project_root: Path, wiki_subdir: str = ".llmwiki") -> Path:
    """Generate .vscode/mcp.json for VS Code Copilot."""
    vscode_dir = project_root / ".vscode"
    vscode_dir.mkdir(exist_ok=True)
    config = {
        "servers": {
            "llmwiki": {
                "type": "stdio",
                "command": "llmwiki",
                "args": ["mcp"],
                "cwd": "${workspaceFolder}/" + wiki_subdir,
            }
        }
    }
    out = vscode_dir / "mcp.json"
    out.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return out


def generate_cursor_mcp(project_root: Path, wiki_subdir: str = ".llmwiki") -> Path:
    """Generate .cursor/mcp.json for Cursor."""
    cursor_dir = project_root / ".cursor"
    cursor_dir.mkdir(exist_ok=True)
    config = {
        "mcpServers": {
            "llmwiki": {
                "command": "llmwiki",
                "args": ["mcp"],
                "cwd": wiki_subdir,
            }
        }
    }
    out = cursor_dir / "mcp.json"
    out.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return out


def generate_jetbrains_mcp(project_root: Path, wiki_subdir: str = ".llmwiki") -> Path:
    """Generate .idea/ai-mcp.json for JetBrains AI."""
    idea_dir = project_root / ".idea"
    idea_dir.mkdir(exist_ok=True)
    config = {
        "mcpServers": {
            "llmwiki": {
                "command": "llmwiki",
                "args": ["mcp"],
                "cwd": wiki_subdir,
            }
        }
    }
    out = idea_dir / "ai-mcp.json"
    out.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return out


def generate_windsurf_mcp(project_root: Path, wiki_subdir: str = ".llmwiki") -> Path:
    """Generate .windsurf/mcp.json for Windsurf."""
    ws_dir = project_root / ".windsurf"
    ws_dir.mkdir(exist_ok=True)
    config = {
        "mcpServers": {
            "llmwiki": {
                "command": "llmwiki",
                "args": ["mcp"],
                "cwd": wiki_subdir,
            }
        }
    }
    out = ws_dir / "mcp.json"
    out.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return out


def generate_copilot_extension(project_root: Path, wiki_subdir: str = ".llmwiki") -> Path:
    """Generate .github/extensions/llmwiki-search.js for Copilot CLI."""
    ext_dir = project_root / ".github" / "extensions"
    ext_dir.mkdir(parents=True, exist_ok=True)
    js = '''// LLMWiki Search Extension for Copilot CLI
// Auto-generated by `llmwiki setup-agent`

const { execSync } = require("child_process");
const path = require("path");

module.exports = [
  {
    name: "llmwiki_search",
    description: "Search the LLMWiki knowledge base. Returns page titles, categories, and snippets. Use this BEFORE reading raw source files to save tokens.",
    parameters: {
      type: "object",
      properties: {
        query: { type: "string", description: "Search query (keywords, method names, or concepts)" },
      },
      required: ["query"],
    },
    execute: async ({ query }) => {
      const wikiDir = path.join(process.cwd(), "''' + wiki_subdir + '''");
      try {
        const result = execSync(`llmwiki search "${query}" --json --config ${wikiDir}/llmwiki.json`, {
          encoding: "utf-8",
          timeout: 10000,
          cwd: wikiDir,
        });
        return result;
      } catch (e) {
        return JSON.stringify({ error: e.message });
      }
    },
  },
];
'''
    out = ext_dir / "llmwiki-search.js"
    out.write_text(js, encoding="utf-8")
    return out


def setup_all(project_root: Path, wiki_subdir: str = ".llmwiki",
              targets: list[str] | None = None) -> list[str]:
    """Generate configs for requested targets. Returns list of created file paths."""
    generators = {
        "vscode": generate_vscode_mcp,
        "cursor": generate_cursor_mcp,
        "jetbrains": generate_jetbrains_mcp,
        "windsurf": generate_windsurf_mcp,
        "copilot_cli": generate_copilot_extension,
    }
    if targets is None:
        targets = list(generators.keys())
    created = []
    for target in targets:
        gen = generators.get(target)
        if gen:
            path = gen(project_root, wiki_subdir)
            created.append(str(path))
    return created
